///\file

/******************************************************************************
The MIT License(MIT)

Embedded Template Library.
https://github.com/TYPHOONCPP/tpn
https://www.tpncpp.com

Copyright(c) 2020 John Wellbelove

Permission is hereby granted" free of charge" to any person obtaining a copy
of this software and associated documentation files(the "Software")" to deal
in the Software without restriction" including without limitation the rights
to use" copy" modify" merge" publi.hpp" distribute" sublicense" and / or sell
copies of the Software" and to permit persons to whom the Software is
furnished to do so" subject to the following conditions :

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS"" WITHOUT WARRANTY OF ANY KIND" EXPRESS OR
IMPLIED" INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY"
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM" DAMAGES OR OTHER
LIABILITY" WHETHER IN AN ACTION OF CONTRACT" TORT OR OTHERWISE" ARISING FROM"
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
******************************************************************************/

#ifndef TYPHOON_FILE_ERROR_NUMBERS
#define TYPHOON_FILE_ERROR_NUMBERS

#define TYPHOON_DEQUE_FILE_ID "1"
#define TYPHOON_FLAT_MAP_FILE_ID "2"
#define TYPHOON_FLAT_MULTIMAP_FILE_ID "3"
#define TYPHOON_FLAT_MULTISET_FILE_ID "4"
#define TYPHOON_FLAT_SET_FILE_ID "5"
#define TYPHOON_FORWARD_LIST_FILE_ID "6"
#define TYPHOON_LIST_FILE_ID "7"
#define TYPHOON_MAP_FILE_ID "8"
#define TYPHOON_MULTIMAP_FILE_ID "9"
#define TYPHOON_MULTISET_FILE_ID "10"
#define TYPHOON_POOL_FILE_ID "11"
#define TYPHOON_PRIORITY_QUEUE_FILE_ID "12"
#define TYPHOON_QUEUE_FILE_ID "13"
#define TYPHOON_SET_FILE_ID "14"
#define TYPHOON_STACK_FILE_ID "15"
#define TYPHOON_UNORDERED_MAP_FILE_ID "16"
#define TYPHOON_VECTOR_FILE_ID "17"
#define TYPHOON_OBSERVER_FILE_ID "18"
#define TYPHOON_IHASH_FILE_ID "19"
#define TYPHOON_INTRUSIVE_FORWARD_LIST_FILE_ID "20"
#define TYPHOON_INTRUSIVE_LIST_FILE_ID "21"
#define TYPHOON_INTRUSIVE_LINKS_FILE_ID "22"
#define TYPHOON_UNORDERED_SET_FILE_ID "23"
#define TYPHOON_VARIANT_FILE_ID "24"
#define TYPHOON_UNORDERED_MULTIMAP_FILE_ID "25"
#define TYPHOON_UNORDERED_MULTISET_FILE_ID "26"
#define TYPHOON_BASIC_STRING_FILE_ID "27"
#define TYPHOON_INTRUSIVE_STACK_FILE_ID "28"
#define TYPHOON_INTRUSIVE_QUEUE_FILE_ID "29"
#define TYPHOON_REFERENCE_FLAT_MAP_FILE_ID "30"
#define TYPHOON_REFERENCE_FLAT_MULTIMAP_FILE_ID "31"
#define TYPHOON_REFERENCE_FLAT_SET_FILE_ID "32"
#define TYPHOON_REFERENCE_FLAT_MULTISET_FILE_ID "33"
#define TYPHOON_FSM_FILE_ID "34"
#define TYPHOON_MESSAGE_ROUTER_FILE_ID "35"
#define TYPHOON_SCHEDULER_FILE_ID "36"
#define TYPHOON_TASK_FILE_ID "37"
#define TYPHOON_MESSAGE_FILE_ID "38"
#define TYPHOON_MESSAGE_BUS_FILE_ID "39"
#define TYPHOON_VARIANT_POOL_FILE_ID "40"
#define TYPHOON_ARRAY_VIEW_FILE_ID "41"
#define TYPHOON_STRING_VIEW_FILE_ID "42"
#define TYPHOON_CALLBACK_TIMER_FILE_ID "43"
#define TYPHOON_MESSAGE_TIMER_FILE_ID "44"
#define TYPHOON_TYPE_LOOKUP_FILE_ID "45"
#define TYPHOON_QUEUE_SPSC_ISR_FILE_ID "46"
#define TYPHOON_QUEUE_SPSC_ATOMIC_FILE_ID "47"
#define TYPHOON_QUEUE_MPMC_MUTEX_FILE_ID "48"
#define TYPHOON_TYPE_SELECT_FILE_ID "49"
#define TYPHOON_BINARY_FILE_ID "50"
#define TYPHOON_DELEGATE_FILE_ID "51"
#define TYPHOON_BITSET_FILE_ID "52"
#define TYPHOON_INDIRECT_VECTOR_FILE_ID "53"
#define TYPHOON_QUEUE_SPSC_LOCKED_FILE_ID "54"
#define TYPHOON_MESSAGE_PACKET_FILE_ID "55"
#define TYPHOON_CIRCULAR_BUFFER_FILE_ID "56"
#define TYPHOON_MULTI_LOOP_FILE_ID "57"
#define TYPHOON_REFERENCE_COUNTER_MESSAGE_POOL_FILE_ID "58"
#define TYPHOON_QUEUE_SPSC_LOCKABLE_FILE_ID "59"
#define TYPHOON_MESSAGE_ROUTER_REGISTRY_FILE_ID "60"
#define TYPHOON_ARRAY_WRAPPER_FILE_ID "61"
#define TYPHOON_MEM_CAST_FILE_ID "62"
#define TYPHOON_SINGLETON_FILE_ID "63"
#define TYPHOON_SUCCESSOR_FILE_ID "64"
#define TYPHOON_BIT_STREAM_FILE_ID "65"
#define TYPHOON_BYTE_STREAM_FILE_ID "66"
#define TYPHOON_BIP_BUFFER_SPSC_ATOMIC_FILE_ID "67"
#define TYPHOON_REFERENCE_COUNTED_OBJECT_FILE_ID "68"
#define TYPHOON_TO_ARITHMETIC_FILE_ID "69"

#endif
